package com.iantimothyjohnson.assignments.project1.dao;

import java.util.List;

import com.iantimothyjohnson.assignments.project1.pojos.Reimbursement;

public interface ReimbursementDAO extends DAO<Reimbursement> {
    /**
     * Queries the database for all reimbursement requests created by the given
     * user.
     * 
     * @param userId the ID of the user who authored the desired reimbursements
     * @return a list of all reimbursements authored by the given user
     */
    List<Reimbursement> selectAllByAuthor(int userId);

    /**
     * Resolves the given reimbursement with the given status and resolver.
     * 
     * Note that this method does not check to ensure that the reimbursement has
     * not already been resolved; resolving a reimbursement will overwrite the
     * previous resolution (this behavior is subject to change, however). The
     * higher-level ReimbursementService is guaranteed to ensure this important
     * condition, however.
     * 
     * @param r          the reimbursement to resolve. The object will be used
     *                   for its ID (to find the reimbursement to update), and
     *                   will be updated with the new status, resolver ID and
     *                   resolved timestamp (generated by the database).
     * @param approved   whether the reimbursement request was approved (if
     *                   false, it was denied)
     * @param resolverId the ID of the user who resolved the request
     * @return whether the reimbursement was updated successfully in the
     *         database
     */
    boolean resolve(Reimbursement r, boolean approved, int resolverId);
}
