package com.ex.dao;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.ex.pojos.Book;
import com.ex.util.ConnectionFactory;

import oracle.jdbc.internal.OracleTypes;

public class BookDao implements Dao<Book, Integer> {

	@Override
	public List<Book> findAll() {
		/*
		 * CALLABLE STATEMENT
		 * 	- extends PreparedStatement
		 * 	- allows us to execute stored procedures
		 * 	- must REGISTER our IN and OUT parameter values and types
		 * 	- IN parameters will be set using setter methods inherited
		 * 	  from PreparedStatement
		 * 	- can return 1 or many ResultSet objects
		 * 
		 * ResultSet
		 * 	- table of data representing a DB result set generated by
		 * 	  executing a SQL statement
		 * 	- maintains a cursor pointing to the current row (however,
		 * 	  it is initially positioned before the first row). The
		 * 	  RS.next() method moves that cursor to each subsequent row
		 * 	  until there are no more rows (returns false)
		 */
		
		List<Book> books = new ArrayList<Book>();
		try (Connection conn = ConnectionFactory.getInstance().getConnection()) {
			String sql = "{call get_all_books(?)}";	// must call inside curly braces
			
			CallableStatement cs = conn.prepareCall(sql);
			cs.registerOutParameter(1, OracleTypes.CURSOR);
			cs.execute();
			
			ResultSet rs = (ResultSet) cs.getObject(1);
			while(rs.next()) {
				Book temp = new Book();
				temp.setId(rs.getInt("Book_Id"));
				temp.setIsbn(rs.getString("ISBN"));
				temp.setPrice(rs.getDouble("price"));
				temp.setTitle(rs.getString("Title"));
				temp.setGenreId(rs.getInt("Genre_Id"));
				books.add(temp);
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return books;
	}

	@Override
	public Book findOne(Integer id) {
		return null;
	}
	
	// Book(id, isbn, title, price, g.getId());
	@Override
	public Book save(Book obj) {
		Book book = new Book();
		return null;
	}

	@Override
	public Book update(Book obj) {
		return null;
	}

	@Override
	public void delete(Book obj) {
		
	}

}
